#!/usr/bin/env bash
# docs-sync.sh — Mirror the human-readable subset of a change to <repo>/docs/changes/<change>/.
#
# This is *always on* for SpecPaper. The docs subfolder is the canonical narrative record
# alongside whatever tracker is configured. Failure here marks the lifecycle stage as blocked.
#
# Usage:
#   docs-sync.sh <specpaper_dir> <change>
#
# Files mirrored: proposal.md, brainstorm.md, spec.md, design.md, verify-report.md, e2e-report.md
# (only those that exist). NOT mirrored: tasks.md, errors.md, learnings.md, status.md,
# .task-context-*, e2e-evidence/, .tracker-ref, .wave-*-issues.json.

set -euo pipefail

usage() { echo "Usage: docs-sync.sh <specpaper_dir> <change>" >&2; exit "${1:-0}"; }
[[ "${1:-}" == "-h" || "${1:-}" == "--help" || $# -lt 2 ]] && usage 1

SPECPAPER_DIR="$1"
CHANGE="$2"
CHANGE_DIR="$SPECPAPER_DIR/changes/$CHANGE"
[[ -d "$CHANGE_DIR" ]] || { echo "Change dir not found: $CHANGE_DIR" >&2; exit 1; }

PROJECT_ROOT="$(cd "$SPECPAPER_DIR/.." && pwd)"

yaml_get() {
  python3 -c "
import yaml
with open('$1') as f: data = yaml.safe_load(f)
keys = '$2'.split('.')
cursor = data
for k in keys:
    if cursor is None: break
    cursor = cursor.get(k) if isinstance(cursor, dict) else None
print('' if cursor is None else cursor)
" 2>/dev/null || true
}

DOCS_ENABLED="$(yaml_get "$SPECPAPER_DIR/config.yaml" "docs.enabled")"
[[ "$DOCS_ENABLED" == "False" || "$DOCS_ENABLED" == "false" ]] && { echo "docs.enabled is false — refusing to skip silently. Re-enable it in .specpaper/config.yaml." >&2; exit 1; }

DOCS_PATH="$(yaml_get "$SPECPAPER_DIR/config.yaml" "docs.path")"
DOCS_PATH="${DOCS_PATH:-docs/changes}"
INDEX_ENABLED="$(yaml_get "$SPECPAPER_DIR/config.yaml" "docs.index")"

DOCS_DIR="$PROJECT_ROOT/$DOCS_PATH/$CHANGE"
mkdir -p "$DOCS_DIR"

# Mirror human-readable artifacts only
for f in proposal.md brainstorm.md spec.md design.md verify-report.md e2e-report.md; do
  if [[ -f "$CHANGE_DIR/$f" ]]; then
    cp "$CHANGE_DIR/$f" "$DOCS_DIR/$f"
  fi
done

echo "[docs-sync] Mirrored $CHANGE → $DOCS_DIR"

# Maintain index.md
if [[ "$INDEX_ENABLED" != "False" && "$INDEX_ENABLED" != "false" ]]; then
  INDEX_FILE="$PROJECT_ROOT/$DOCS_PATH/index.md"
  {
    echo "# Changes"
    echo
    echo "_Auto-generated by SpecPaper — do not edit by hand._"
    echo
    echo "| Change | Status | Proposal | Spec | Design | Verify | E2E |"
    echo "|---|---|---|---|---|---|---|"
    for dir in "$PROJECT_ROOT/$DOCS_PATH"/*/; do
      [[ -d "$dir" ]] || continue
      name="$(basename "$dir")"
      [[ "$name" == "index.md" ]] && continue
      # status hint from local .specpaper if available
      local_status_file="$SPECPAPER_DIR/changes/$name/status.md"
      status="active"
      if [[ -f "$local_status_file" ]]; then
        status="$(grep -m1 -E '^Status:' "$local_status_file" | sed 's/Status:[[:space:]]*//' || echo active)"
      fi
      [[ -d "$SPECPAPER_DIR/changes/archive/$name" ]] && status="archived"
      tick() { [[ -f "$dir/$1" ]] && echo "✓" || echo "—"; }
      echo "| [$name](./$name/) | $status | $(tick proposal.md) | $(tick spec.md) | $(tick design.md) | $(tick verify-report.md) | $(tick e2e-report.md) |"
    done
  } > "$INDEX_FILE"
  echo "[docs-sync] Updated index: $INDEX_FILE"
fi
